server:
  port: 8080


spring:
  rabbitmq:
    host: 192.168.1.188
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true
